using System;
namespace Dangl.SevDeskExport
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionInfo
    {
        public static string Version => "1.5.0-beta0005";
        public static string CommitInfo => "Branch.develop.Sha.bfdf9de9805bab36c8bca4e14a7467cd32adc44e";
        public static string CommitDate => "2022-06-07";
        public static string CommitHash => "bfdf9de9805bab36c8bca4e14a7467cd32adc44e";
        public static string InformationalVersion => "1.5.0-beta.5+Branch.develop.Sha.bfdf9de9805bab36c8bca4e14a7467cd32adc44e";
        public static DateTime BuildDateUtc => new DateTime(2022, 6, 7, 20, 0, 36, DateTimeKind.Utc);
    }
}