using System;
namespace Dangl.SevDeskExport
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionInfo
    {
        public static string Version => "0.1.1-beta0003";
        public static string CommitInfo => "Branch.develop.Sha.93b5bf748705bb89bd18132fffe7b13c2212ad95";
        public static string CommitDate => "2020-02-14";
        public static string CommitHash => "93b5bf748705bb89bd18132fffe7b13c2212ad95";
        public static string InformationalVersion => "0.1.1-beta.3+Branch.develop.Sha.93b5bf748705bb89bd18132fffe7b13c2212ad95";
        public static DateTime BuildDateUtc => new DateTime(2020, 2, 14, 21, 34, 54, DateTimeKind.Utc);
    }
}